export function getRandomName(): string {
	const adjectives = [
		"Vui vẻ",
		"Thông minh",
		"Dũng cảm",
		"Nhẹ nhàng",
		"Sáng suốt",
		"May mắn",
		"Tốt bụng",
		"Ngầu",
		"Bình tĩnh",
		"Tỏa sáng",
		"Khéo léo",
		"Nhanh nhẹn",
		"Cao quý",
		"Ngọt ngào",
		"Vui nhộn",
		"Phấn khởi",
		"Tự hào",
		"Nhiệt tình",
		"Lanh lợi",
		"Rực rỡ",
		"Sôi nổi",
		"Nghịch ngợm",
		"Thân thiện",
		"Yên tĩnh",
		"Vui tươi",
		"Thanh lịch",
		"Trung thực",
		"Dễ thương",
		"Quyến rũ",
		"Táo bạo",
		"Tràn đầy năng lượng",
		"Hài hước",
		"Khiêm tốn",
		"Kỳ diệu",
		"Mạnh mẽ",
		"Kiên nhẫn",
		"Lộng lẫy",
		"Lấp lánh",
		"Tinh nghịch",
		"Đáng yêu",
	];
	const animals = [
		"Mèo",
		"Chó",
		"Cáo",
		"Gấu",
		"Cú",
		"Sói",
		"Sư tử",
		"Hổ",
		"Gấu trúc",
		"Thỏ",
		"Hươu con",
		"Vịt",
		"Chim nhỏ",
		"Cá",
		"Hải cẩu",
		"Cá heo",
		"Chim cánh cụt",
		"Gấu koala",
		"Chuột túi",
		"Voi",
		"Hươu cao cổ",
		"Khỉ",
		"Ngựa vằn",
		"Nhím",
		"Sóc",
		"Chuột hamster",
		"Gấu mèo",
		"Bướm",
		"Rồng",
		"Kỳ lân",
		"Cá voi",
		"Rái cá",
		"Ngựa con",
		"Lạc đà không bướu",
		"Hải ly",
		"Báo săn",
		"Đại bàng",
		"Cắt (chim săn mồi)",
		"Linh dương",
		"Hà mã",
	];
	const randomAdjective =
		adjectives[Math.floor(Math.random() * adjectives.length)];
	const randomAnimal = animals[Math.floor(Math.random() * animals.length)];
	return `${randomAdjective}${randomAnimal}`;
}
